name: GitHub-Profile-3D-Contrib

on:
  push:
    branches:
      - main
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: push profile-3d-contrib
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: profile-3d-contrib
          build_dir: profile-3d-contrib
          author: xiaoyu98628 <1765841705@qq.com>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}